### ISSUE TITLE
error when running landscape script

### ISSUE THREAD

**Issue by kabirbg** [zzzeyez/landscape#1]
When i run the `landscape` script provided, I got the following error (exit code 1):
```
execution error: The variable refresh is not defined. (-2753)
```
I skimmed through the landscape.jsx widget and the landscape.css configuration, as well as the shell script itself, but I couldn't really find what was wrong. At the top of my screen I see this (when I have 5 workspaces, and the 4th is where my terminal is (where i executed ./landscape from):
<img width="332" alt="Screen Shot 2021-01-16 at 6 17 36 PM" src="https://user-images.githubusercontent.com/56413904/104827767-1db06380-5827-11eb-8009-2cad616a5617.png">

I'm using landscape in conjunction with yabai and pecan; I just cloned the git repo again and ran the script and got the same problem, so there have been no changes from default (apart from what the script did). 

Also, I have uebersicht set up to look for widgets at ~/.config/uebersicht/widgets rather than ~/Library/Application Support/Übersicht/widgets; that shouldn't make a difference I would think but perhaps it does because landscape was working fine until I made that change. Is there a place in the code that requires the folder to be in a particular location, something I missed? If that's the case I can manually edit it.

Thanks in advance!

**Comment by zzzeyez** [comment]
did you try restarting it?  sometimes i do have this error occur as well.  your widget location should not matter.

**Comment by zzzeyez** [comment]
also: i have seen skhd play funky with uebersicht if you start it by using 'brew services start skhd'.  try doing 'skhd & disown' instead

**Comment by kabirbg** [comment]
> did you try restarting it? sometimes i do have this error occur as well. your widget location should not matter.

yup, restarting doesn't seem to have fixed it (and neither did temporarily changing the widget location). do you think there could be some macos permissions that need to be granted to let it display the other spaces too?

> also: i have seen skhd play funky with uebersicht if you start it by using 'brew services start skhd'. try doing 'skhd & disown' instead

hm ok, i changed that now and restarted uebersicht. i also reran the landscape script but not sure why it doesn't seem to have made a difference (to be clear, i know it's running because the image of the terminal at the top updates to the way it currently looks, but it's just not displaying the other four spaces)

this may be a problem just on my end, thanks for your help though!

**Comment by zzzeyez** [comment]
oh btw!  i should be clear.  those images are updated as you switch to the new workspaces.  when you switch to workspace three the image is created for workspace 3 by using the 'landscape' script

**Comment by kabirbg** [comment]
ooh, i think that fixed it -- it completely slipped my mind to run the landscape script *in addition* to refreshing the landscape widget everytime i switched workspace in my yabairc. thank you so much!
